[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.13"
fs_permissions = [{ access = true, path = "./"}]

[fmt]
line_length = 75

[rpc_endpoints]
anvil = "http://localhost:8545/"
goerli = "https://ethereum-goerli-rpc.allthatnode.com"
sepolia = "https://ethereum-sepolia-rpc.allthatnode.com"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}" }




# See more config options https://github.com/foundry-rs/foundry/tree/master/config