[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
fs_permissions = [{ access = true, path = "./"}]

[fmt]
line_length = 75

[rpc_endpoints]
anvil = "http://localhost:8545/"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}" }




# See more config options https://github.com/foundry-rs/foundry/tree/master/config